name: Java Maven Build and Test
on: [push]
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
       distribution: 'adopt'
       java-version: '11'
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build with Maven
      run: mvn clean package

    - name: Test with Maven
      run: mvn test
