name: catraca ci nativo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: jdk setup
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: install maven
      run: sudo apt-get install maven
    - name: build with maven
      run: mvn package
    - name: exec
      run: |
        cd target
        java -jar <your_jar_file_name>.jar
    - uses: mr-smithers-excellent/docker-build-push@v6
      name: subindo no docker
      with:
        image: ${{secrets.DOCKER_USERNAME}}/catraca
        tags: 1.0
        registry: docker.io
        dockerfile: dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: versioning
      uses: codacy/git-version@2.4.0
      with:
        release-branch: main
